[package]
name = "synchrotron"
version = "0.1.0"
authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]

[profile.release]
debug = true
lto = true

[dependencies]
log = "0.4"
slog = "2.2.3"
slog-async = "2.2.0"
slog-scope = "4.0.1"
slog-stdlog = "3.0.2"
slog-term = "2.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1.5"
tokio-io = "0.1.6"
futures = "0.1"
net2 = "0.2.32"
rs-futures-spmc = { git = "https://github.com/mredlek/rs-futures-spmc" }
multiqueue = "0.3.2"
chan = "0.1.19"
chan-signal = "0.3.1"
bytes = "0.4"
atoi = "0.2.3"
itoa = "0.4.1"
rand = "0.5.0-pre.0"

[dev-dependencies]
spectral = "0.6.0"
matches = "0.1.6"
