[package]
name = "synchrotron"
version = "0.1.0"
authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]

[profile.release]
debug = true
lto = true

[dependencies]
log = "^0.4"
slog = "^2.2"
slog-async = "^2.2"
slog-scope = "^4.0"
slog-stdlog = "^3.0"
slog-term = "^2.3"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
tokio = "^0.1"
tokio-io = "^0.1"
futures = "^0.1.21"
net2 = "^0.2"
rs-futures-spmc = { git = "https://github.com/nuclearfurnace/rs-futures-spmc" }
chan = "^0.1"
chan-signal = "^0.3"
bytes = "^0.4"
atoi = "^0.2"
itoa = "^0.4"
rand = "^0.5"
rust-crypto = "^0.2"
pruefung = "^0.2"

[dependencies.config]
version = "^0.8"
default-features = false
features = ["json"]

[dev-dependencies]
spectral = "^0.6"
matches = "^0.1"
